### PR TITLE
Fix GC deleting values without expiry 

### LINKED ISSUE #53: Postgres - No Expiry not working
When I use postgres storage, I tried to set 0 for no expiry... but the keys are expiring when set to 0

### PR DESCRIPTION
**Pull request by hi019**
Fixes #53

### CODE REVIEW

File: mysql/mysql.go [hunk 1]
```diff
@@ -160,16 +160,21 @@ func (s *Storage) Close() error {
 	return s.db.Close()
 }
 
-// Garbage collector to delete expired keys
-func (s *Storage) gc() {
+// gcTicker starts the gc ticker
```
Comment (hi019) [inline mysql/mysql.go:163]: I have separated the GC & GC ticker func so that it's easier to test

**Review by ReneWerner87 — APPROVED** [review]
